### ISSUE TITLE
I have some troubles with the production build

### ISSUE THREAD

**Issue by nik0xFF** [ChihoSin/generator-jhipster-vmware-clarity#1]
I was evaluating your generator with the 4.14.x and 5.0.0-beta1 version of jhipster.  The dev build of the beta succeeded but not its production one. So I wanted to ask you if this is a known issue. 
Please see the attached log excerpt below for the issue's details 
Thank you for sharing your work by the way!

Regards 

Nik

**Comment by nik0xFF** [comment]
`ERROR in (1,1): : Directive ɵca, Property 'block' does not exist on type 'ClrDatagridColumnToggleButton'.
node_modules\@clr\angular\clr-angular.d.ts.ClrHeader.html(6,13): : Property 'NAV_LEVEL_1' does not exist on type 'ResponsiveNavCodes'.
node_modules\@clr\angular\clr-angular.d.ts.ClrHeader.html(14,13): : Property 'NAV_LEVEL_2' does not exist on type 'ResponsiveNavCodes'.
src\main\webapp\app\layouts\main\main.component.html(1,361): : Property 'router' is private and only accessible within class 'JhiMainComponent'.
src\main\webapp\app\layouts\navbar\navbar.component.html(1,1531): : Directive ClrDropdownTrigger, Property 'isRootLevelToggle' is private and only accessible within class 'ClrDropdownTrigger'.
src\main\webapp\app\layouts\navbar\navbar.component.html(1,1531): : Directive ClrDropdownTrigger, Property 'isRootLevelToggle' is private and only accessible within class 'ClrDropdownTrigger'.
src\main\webapp\app\layouts\navbar\navbar.component.html(1,1531): : Directive ClrDropdownTrigger, Property 'isRootLevelToggle' is private and only accessible within class 'ClrDropdownTrigger'.
src\main\webapp\app\layouts\navbar\navbar.component.html(1,1093): : Directive ClrDropdownTrigger, Property 'isRootLevelToggle' is private and only accessible within class 'ClrDropdownTrigger'.
src\main\webapp\app\layouts\navbar\navbar.component.html(1,1093): : Directive ClrDropdownTrigger, Property 'isRootLevelToggle' is private and only accessible within class 'ClrDropdownTrigger'.
src\main\webapp\app\layouts\navbar\navbar.component.html(1,1093): : Directive ClrDropdownTrigger, Property 'isRootLevelToggle' is private and only accessible within class 'ClrDropdownTrigger'.
src\main\webapp\app\layouts\navbar\navbar.component.html(1,590): : Directive ClrDropdownTrigger, Property 'isRootLevelToggle' is private and only accessible within class 'ClrDropdownTrigger'.
src\main\webapp\app\layouts\navbar\navbar.component.html(1,590): : Directive ClrDropdownTrigger, Property 'isRootLevelToggle' is private and only accessible within class 'ClrDropdownTrigger'.
src\main\webapp\app\layouts\navbar\navbar.component.html(1,590): : Directive ClrDropdownTrigger, Property 'isRootLevelToggle' is private and only accessible within class 'ClrDropdownTrigger'.
src\main\webapp\app\layouts\sidebar\sidebar.component.html(1,35): : Property 'router' is private and only accessible within class 'SidebarComponent'.
src\main\webapp\app\admin\user-management\user-management-delete-dialog.component.html(1,237): : Property 'item' is private and only accessible within class 'UserMgmtDeleteDialogComponent'.
src\main\webapp\app\admin\user-management\user-management-delete-dialog.component.html(1,237): : Property 'name' does not exist on type 'User'.
src\main\webapp\app\admin\user-management\user-management-delete-dialog.component.html(1,494): : Property 'confirmDelete' does not exist on type 'UserMgmtDeleteDialogComponent'.
src\main\webapp\app\admin\user-management\user-management-delete-dialog.component.html(1,494): : Property 'item' is private and only accessible within class 'UserMgmtDeleteDialogComponent'.
src\main\webapp\app\admin\user-management\user-management-delete-dialog.component.html(1,940): : Property 'list' is private and only accessible within class 'UserMgmtDeleteDialogComponent'.
src\main\webapp\app\admin\user-management\user-management-delete-dialog.component.html(1,1123): : Property 'list' is private and only accessible within class 'UserMgmtDeleteDialogComponent'.
src\main\webapp\app\admin\user-management\user-management-delete-dialog.component.html(1,1268): : Property 'progressValue' is private and only accessible within class 'UserMgmtDeleteDialogComponent'.
src\main\webapp\app\admin\user-management\user-management-delete-dialog.component.html(1,1268): : Property 'list' is private and only accessible within class 'UserMgmtDeleteDialogComponent'.
src\main\webapp\app\admin\user-management\user-management-delete-dialog.component.html(1,1268): : Property 'progressValue' is private and only accessible within class 'UserMgmtDeleteDialogComponent'.
src\main\webapp\app\admin\user-management\user-management-delete-dialog.component.html(1,1268): : Property 'list' is private and only accessible within class 'UserMgmtDeleteDialogComponent'.
src\main\webapp\app\admin\user-management\user-management-delete-dialog.component.html(1,1268): : Property 'progressValue' is private and only accessible within class 'UserMgmtDeleteDialogComponent'.
src\main\webapp\app\admin\user-management\user-management-delete-dialog.component.html(1,1268): : Property 'name' does not exist on type 'User'.
src\main\webapp\app\admin\user-management\user-management-delete-dialog.component.html(1,1505): : Property 'progressValue' is private and only accessible within class 'UserMgmtDeleteDialogComponent'.
src\main\webapp\app\admin\user-management\user-management-delete-dialog.component.html(1,1505): : Property 'list' is private and only accessible within class 'UserMgmtDeleteDialogComponent'.
src\main\webapp\app\admin\user-management\user-management-delete-dialog.component.html(1,1505): : Property 'progressValue' is private and only accessible within class 'UserMgmtDeleteDialogComponent'.
src\main\webapp\app\admin\user-management\user-management-delete-dialog.component.html(1,1505): : Property 'list' is private and only accessible within class 'UserMgmtDeleteDialogComponent'.
src\main\webapp\app\admin\user-management\user-management-delete-dialog.component.html(1,1505): : Property 'progressValue' is private and only accessible within class 'UserMgmtDeleteDialogComponent'.
src\main\webapp\app\admin\user-management\user-management-delete-dialog.component.html(1,1505): : Property 'name' does not exist on type 'User'.
src\main\webapp\app\admin\user-management\user-management-delete-dialog.component.html(1,1717): : Property 'progressState' is private and only accessible within class 'UserMgmtDeleteDialogComponent'.
src\main\webapp\app\admin\user-management\user-management-delete-dialog.component.html(1,1759): : Property 'progressState' is private and only accessible within class 'UserMgmtDeleteDialogComponent'.
src\main\webapp\app\admin\user-management\user-management-delete-dialog.component.html(1,1815): : Property 'list' is private and only accessible within class 'UserMgmtDeleteDialogComponent'.
src\main\webapp\app\admin\user-management\user-management-delete-dialog.component.html(1,1837): : Property 'progressState' is private and only accessible within class 'UserMgmtDeleteDialogComponent'.
src\main\webapp\app\admin\user-management\user-management-delete-dialog.component.html(1,1837): : Property 'list' is private and only accessible within class 'UserMgmtDeleteDialogComponent'.
src\main\webapp\app\admin\user-management\user-management-delete-dialog.component.html(1,1837): : Property 'progressValue' is private and only accessible within class 'UserMgmtDeleteDialogComponent'.
src\main\webapp\app\admin\user-management\user-management-delete-dialog.component.html(1,1922): : Property 'progressState' is private and only accessible within class 'UserMgmtDeleteDialogComponent'.
src\main\webapp\app\admin\user-management\user-management-delete-dialog.component.html(1,1922): : Property 'list' is private and only accessible within class 'UserMgmtDeleteDialogComponent'.
src\main\webapp\app\admin\user-management\user-management-delete-dialog.component.html(1,1922): : Property 'progressValue' is private and only accessible within class 'UserMgmtDeleteDialogComponent'.
src\main\webapp\app\admin\user-management\user-management-delete-dialog.component.html(1,1922): : Property 'list' is private and only accessible within class 'UserMgmtDeleteDialogComponent'.
src\main\webapp\app\admin\user-management\user-management-delete-dialog.component.html(1,686): : Property 'progressState' is private and only accessible within class 'UserMgmtDeleteDialogComponent'.
src\main\webapp\app\admin\user-management\user-management-delete-dialog.component.html(1,634): : Property 'progressState' is private and only accessible within class 'UserMgmtDeleteDialogComponent'.
src\main\webapp\app\admin\user-management\user-management-delete-dialog.component.html(1,856): : Property 'progressState' is private and only accessible within class 'UserMgmtDeleteDialogComponent'.
src\main\webapp\app\admin\user-management\user-management-delete-dialog.component.html(1,1038): : Property 'progressState' is private and only accessible within class 'UserMgmtDeleteDialogComponent'.
src\main\webapp\app\admin\user-management\user-management-delete-dialog.component.html(1,1187): : Property 'progressState' is private and only accessible within class 'UserMgmtDeleteDialogComponent'.
src\main\webapp\app\admin\user-management\user-management-delete-dialog.component.html(1,1415): : Property 'progressState' is private and only accessible within class 'UserMgmtDeleteDialogComponent'.
src\main\webapp\app\admin\user-management\user-management-delete-dialog.component.html(1,1659): : Property 'progressState' is private and only accessible within class 'UserMgmtDeleteDialogComponent'.
src\main\webapp\app\admin\user-management\user-management-delete-dialog.component.html(1,2064): : Property 'progressState' is private and only accessible within class 'UserMgmtDeleteDialogComponent'.
src\main\webapp\app\admin\user-management\user-management-delete-dialog.component.html(1,2217): : Property 'progressState' is private and only accessible within class 'UserMgmtDeleteDialogComponent'.
src\main\webapp\app\admin\user-management\user-management-delete-dialog.component.html(1,2378): : Property 'progressState' is private and only accessible within class 'UserMgmtDeleteDialogComponent'.
src\main\webapp\app\admin\user-management\user-management-delete-dialog.component.html(1,2378): : Property 'progressState' is private and only accessible within class 'UserMgmtDeleteDialogComponent'.
src\main\webapp\app\admin\user-management\user-management-delete-dialog.component.html(1,60): : Property 'item' is private and only accessible within class 'UserMgmtDeleteDialogComponent'.
src\main\webapp\app\admin\user-management\user-management-delete-dialog.component.html(1,573): : Property 'list' is private and only accessible within class 'UserMgmtDeleteDialogComponent'.
src\main\webapp\app\admin\health\health-modal.component.html(1,261): : Property 'activeModal' does not exist on type 'JhiHealthModalComponent'.
src\main\webapp\app\admin\health\health-modal.component.html(1,1165): : Property 'activeModal' does not exist on type 'JhiHealthModalComponent'.
src\main\webapp\app\admin\metrics\metrics.component.html(1,2301): : Property 'refreshThreadDumpData' does not exist on type 'JhiMetricsMonitoringComponent'.
src\main\webapp\app\admin\metrics\metrics-modal.component.html(1,153): : Property 'activeModal' does not exist on type 'JhiMetricsMonitoringModalComponent'.
src\main\webapp\app\admin\metrics\metrics-modal.component.html(1,2980): : Property 'activeModal' does not exist on type 'JhiMetricsMonitoringModalComponent'.
`

**Comment by chihosin** [comment]
I think it's error throw from tslint, we well fix the code specification as soon as passable.
