### ISSUE TITLE
Using clarity icon set replace boolean value

### ISSUE THREAD

**Issue by chihosin** [ChihoSin/generator-jhipster-vmware-clarity#6]
![image](https://user-images.githubusercontent.com/4188078/40478183-f789c86a-5f7a-11e8-8f69-0f5f89254c6d.png)

**Comment by chihosin** [comment]
![image](https://user-images.githubusercontent.com/4188078/40478223-0e4f725c-5f7b-11e8-8654-f19f7c4ab108.png)

**Comment by little-snow-fox** [comment]
added
