### ISSUE TITLE
upgrade to jhipster 5.1.0

### ISSUE THREAD

**Issue by kpolszewski** [ChihoSin/generator-jhipster-vmware-clarity#7]
are you planning on upgrading this module to jhipster 5(using angular 6) any time soon? or is it a PR material?

**Comment by kpolszewski** [comment]
sorry, totally irrelevant, your generator already works on it... seems to be other problem, on my side, as even dependencies are not added to packages.json

**Comment by kpolszewski** [comment]
still, invoking generator on jhipster 5.1.0 projects with i18n ends up with exception:
```
  someproject git:(master) ✗ yo jhipster-vmware-clarity

██████╗ ██╗ ██████╗ ██████╗ ██╗   ██╗ ██████╗
██╔══██╗██║██╔════╝ ██╔══██╗██║   ██║██╔════╝
██████╔╝██║██║  ███╗██████╔╝██║   ██║██║  ███╗
██╔══██╗██║██║   ██║██╔══██╗██║   ██║██║   ██║
██████╔╝██║╚██████╔╝██████╔╝╚██████╔╝╚██████╔╝
╚═════╝ ╚═╝ ╚═════╝ ╚═════╝  ╚═════╝  ╚═════╝
Running JHipster VMware Clarity Generator! v1.1.1

Removing the file - src/main/webapp/app/layouts/profiles/page-ribbon.component.ts
Removing the file - src/main/webapp/app/blocks/config/uib-pagination.config.ts
Removing the file - src/main/webapp/app/core/login/login-modal.service.ts
Removing the folder - src/main/webapp/app/layouts/footer
Removing the folder - src/main/webapp/app/shared/login
events.js:183
      throw er; // Unhandled 'error' event
      ^

AssertionError [ERR_ASSERTION]: When copying multiple files, provide a directory as destination
    at EditionInterface.exports.copy (/mnt/c/someproject/node_modules/mem-fs-editor/lib/actions/copy.js:35:5)
    at module.exports.copy (/mnt/c/someproject/node_modules/generator-jhipster/generators/generator-base-private.js:666:17)
    at module.exports.copyI18nFilesByName (/mnt/c/someproject/node_modules/generator-jhipster/generators/generator-base.js:1839:15)
    at module.exports.installI18nClientFilesByLanguage (/mnt/c/someproject/node_modules/generator-jhipster/generators/generator-base-private.js:75:23)
    at languages.forEach (/mnt/c/someproject/node_modules/generator-jhipster-vmware-clarity/generators/app/index.js:845:22)
    at Array.forEach (<anonymous>)
    at module.exports.writing (/mnt/c/someproject/node_modules/generator-jhipster-vmware-clarity/generators/app/index.js:844:28)
    at Object.<anonymous> (/mnt/c/someproject/node_modules/yeoman-generator/lib/index.js:399:25)
    at /mnt/c/someproject/node_modules/run-async/index.js:25:25
    at new Promise (<anonymous>)
➜  someproject git:(master) ✗ jhipster --version
Using JHipster version installed locally in current project's node_modules
5.1.0
➜  someproject git:(master) ✗
```

**Comment by HaithemSouala** [comment]
HI @kpolszewski 

Did you solve the problem?

**Comment by kpolszewski** [comment]
Sadly, no. Currently I do not have time to look into it, but I am planning on it in close future.

**Comment by HaithemSouala** [comment]
OK, thank you.

**Comment by chihosin** [comment]
The vmware clarity project is package by angular-cli, is not compatible for custom setting webpack.
If you want to upgrade jhipster version to 5.1.0, you need to change the frontend framework, build with angular-cli.

It's horrible suggestion!

**Comment by kpolszewski** [comment]
Could you post some reference post/article to the difference between versions you are describing? 
Furthermore, your generator currently shows up on JHipster's 5.1.0 generators list, is it possible to adjust it if it won't work on this version and add some info to the README regarding versions that it runs on? It is hard to get up going without this.

We are just users of solution you open-sourced, so your attitude and assumption that we know everything about problems you are having while developing this generator is simply wrong. Also, it looks like you have made this software in order to support your current projects, in that case, it is understandable to be locked on some older version of JHipster. However, from the community's perspective, doing it is a show-stopper for using it, and that is pretty sad keeping in mind that you have published it on MIT license.

**Comment by chihosin** [comment]
![image](https://user-images.githubusercontent.com/4188078/43753541-e96134dc-9a38-11e8-9c93-1b54df42775c.png)

I don't have free time to follow JHipster to update the version of this repository.
If you are interested in it, i hope you can fork this project and improve it!

MIT license means you using my code for free, but it doesn't mean I need to serve you. @kpolszewski
